# Generated by Django 4.0.6 on 2022-07-14 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_scope_options_alter_scopeposition_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopeposition',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.scope', verbose_name='Раздел'),
        ),
    ]
