# Generated by Django 4.0.6 on 2022-07-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_scopeposition_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopeposition',
            name='basic',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
