# Generated by Django 4.0.6 on 2022-07-15 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_articlescope_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlescope',
            old_name='basic',
            new_name='is_main',
        ),
        migrations.AlterField(
            model_name='articlescope',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article'),
        ),
    ]
