# Generated by Django 4.0.6 on 2022-07-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_rename_basic_articlescope_is_main_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlescope',
            old_name='is_main',
            new_name='basic',
        ),
    ]
