# Generated by Django 4.0.6 on 2022-07-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_rename_is_main_articlescope_basic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlescope',
            old_name='basic',
            new_name='is_main',
        ),
    ]
