# Generated by Django 4.0.6 on 2022-07-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_rename_basic_articlescope_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescope',
            options={'ordering': ['is_main'], 'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематики статьи'},
        ),
    ]
